---
abstract: 'mod_rewrite for Plack'
author:
  - 'Aristotle Pagaltzis <pagaltzis@gmx.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Rewrite
resources:
  bugtracker: http://github.com/ap/Plack-Middleware-Rewrite/issues
  homepage: http://github.com/ap/Plack-Middleware-Rewrite
  repository: git://github.com/ap/Plack-Middleware-Rewrite
version: 1.0
